CREATE TABLE  "ACADEMICYEAR" 
   (	"YEARID" NUMBER(5,0), 
	"YEARNAME" VARCHAR2(20), 
	 PRIMARY KEY ("YEARID") ENABLE
   ) ;CREATE TABLE  "COLLEGE" 
   (	"COLLEGEID" NUMBER(5,0), 
	"COLLEGENAME" VARCHAR2(100), 
	 PRIMARY KEY ("COLLEGEID") ENABLE, 
	 UNIQUE ("COLLEGENAME") ENABLE
   ) ;CREATE TABLE  "PROGRAMSTUDY" 
   (	"STUDYID" NUMBER(5,0), 
	"FIELDOFSTUDYID" NUMBER(5,0), 
	 PRIMARY KEY ("STUDYID") ENABLE
   ) ;CREATE TABLE  "CURRICULUM" 
   (	"CURRICULUMID" NUMBER(5,0), 
	"PROGRAMSTUDYID" NUMBER(5,0), 
	 PRIMARY KEY ("CURRICULUMID") ENABLE
   ) ;CREATE TABLE  "DEPARTMENT" 
   (	"DEPARTMENTID" NUMBER(5,0), 
	"DEPARTMENTNAME" VARCHAR2(100), 
	"COLLEGEID" NUMBER(5,0), 
	 PRIMARY KEY ("DEPARTMENTID") ENABLE, 
	 UNIQUE ("DEPARTMENTNAME") ENABLE
   ) ;CREATE TABLE  "FIELDOFSTUDY" 
   (	"FIELDID" NUMBER(5,0), 
	"FIELDNAME" VARCHAR2(100), 
	"DEPARTMENTID" NUMBER(5,0), 
	 PRIMARY KEY ("FIELDID") ENABLE, 
	 UNIQUE ("FIELDNAME") ENABLE
   ) ;CREATE TABLE  "PROGRAMADMISSION" 
   (	"ADMISSIONID" NUMBER(5,0), 
	"ADMISSIONNAME" VARCHAR2(100), 
	 PRIMARY KEY ("ADMISSIONID") ENABLE
   ) ;CREATE TABLE  "PROGRAMAWARD" 
   (	"AWARDID" NUMBER(5,0), 
	"AWARDNAME" VARCHAR2(100), 
	 PRIMARY KEY ("AWARDID") ENABLE
   ) ;CREATE TABLE  "PROGRAMENTRY" 
   (	"ENTRYID" NUMBER(5,0), 
	"ENTRYTYPE" VARCHAR2(100), 
	"CURRICULUMID" NUMBER(5,0), 
	 PRIMARY KEY ("ENTRYID") ENABLE
   ) ;CREATE TABLE  "STUDENT" 
   (	"STUDENTID" NUMBER(10,0), 
	"FULLNAME" VARCHAR2(100), 
	"COLLEGEID" NUMBER(5,0), 
	"DEPARTMENTID" NUMBER(5,0), 
	"FIELDID" NUMBER(5,0), 
	"AWARDID" NUMBER(5,0), 
	"STUDYID" NUMBER(5,0), 
	"YEARID" NUMBER(5,0), 
	"CURRICULUMID" NUMBER(5,0), 
	"ENTRYID" NUMBER(5,0), 
	 PRIMARY KEY ("STUDENTID") ENABLE
   ) ;ALTER TABLE  "STUDENT" ADD CONSTRAINT "FK_AWARD_STUDENT" FOREIGN KEY ("AWARDID")
	  REFERENCES  "PROGRAMAWARD" ("AWARDID") ENABLE;ALTER TABLE  "DEPARTMENT" ADD CONSTRAINT "FK_COLLEGE" FOREIGN KEY ("COLLEGEID")
	  REFERENCES  "COLLEGE" ("COLLEGEID") ENABLE;ALTER TABLE  "STUDENT" ADD CONSTRAINT "FK_COLLEGE_STUDENT" FOREIGN KEY ("COLLEGEID")
	  REFERENCES  "COLLEGE" ("COLLEGEID") ENABLE;ALTER TABLE  "PROGRAMENTRY" ADD CONSTRAINT "FK_CURRICULUM" FOREIGN KEY ("CURRICULUMID")
	  REFERENCES  "CURRICULUM" ("CURRICULUMID") ENABLE;ALTER TABLE  "STUDENT" ADD CONSTRAINT "FK_CURRICULUM_STUDENT" FOREIGN KEY ("CURRICULUMID")
	  REFERENCES  "CURRICULUM" ("CURRICULUMID") ENABLE;ALTER TABLE  "FIELDOFSTUDY" ADD CONSTRAINT "FK_DEPARTMENT" FOREIGN KEY ("DEPARTMENTID")
	  REFERENCES  "DEPARTMENT" ("DEPARTMENTID") ENABLE;ALTER TABLE  "STUDENT" ADD CONSTRAINT "FK_DEPARTMENT_STUDENT" FOREIGN KEY ("DEPARTMENTID")
	  REFERENCES  "DEPARTMENT" ("DEPARTMENTID") ENABLE;ALTER TABLE  "STUDENT" ADD CONSTRAINT "FK_ENTRY_STUDENT" FOREIGN KEY ("ENTRYID")
	  REFERENCES  "PROGRAMENTRY" ("ENTRYID") ENABLE;ALTER TABLE  "PROGRAMSTUDY" ADD CONSTRAINT "FK_FIELD_OF_STUDY" FOREIGN KEY ("FIELDOFSTUDYID")
	  REFERENCES  "FIELDOFSTUDY" ("FIELDID") ENABLE;ALTER TABLE  "STUDENT" ADD CONSTRAINT "FK_FIELD_STUDENT" FOREIGN KEY ("FIELDID")
	  REFERENCES  "FIELDOFSTUDY" ("FIELDID") ENABLE;ALTER TABLE  "CURRICULUM" ADD CONSTRAINT "FK_PROGRAM_STUDY" FOREIGN KEY ("PROGRAMSTUDYID")
	  REFERENCES  "PROGRAMSTUDY" ("STUDYID") ENABLE;ALTER TABLE  "STUDENT" ADD CONSTRAINT "FK_STUDY_STUDENT" FOREIGN KEY ("STUDYID")
	  REFERENCES  "PROGRAMSTUDY" ("STUDYID") ENABLE;ALTER TABLE  "STUDENT" ADD CONSTRAINT "FK_YEAR_STUDENT" FOREIGN KEY ("YEARID")
	  REFERENCES  "ACADEMICYEAR" ("YEARID") ENABLE;
CREATE OR REPLACE FUNCTION  "CUSTOM_HASH" (p_username in varchar2, p_password in varchar2)
return varchar2
is
  l_password varchar2(4000);
  l_salt varchar2(4000) := '2J4ZV36B1ZJG0NKXOMHQERHKL1JAKF';
begin

-- This function should be wrapped, as the hash algorhythm is exposed here.
-- You can change the value of l_salt or the method of which to call the
-- DBMS_OBFUSCATOIN toolkit, but you much reset all of your passwords
-- if you choose to do this.

l_password := utl_raw.cast_to_raw(dbms_obfuscation_toolkit.md5
  (input_string => p_password || substr(l_salt,10,13) || p_username ||
    substr(l_salt, 4,10)));
return l_password;
end;
/
/
CREATE OR REPLACE FUNCTION  "CUSTOM_AUTH" (p_username in VARCHAR2, p_password in VARCHAR2)
return BOOLEAN
is
  l_password varchar2(4000);
  l_stored_password varchar2(4000);
  l_expires_on date;
  l_count number;
begin
-- First, check to see if the user is in the user table
select count(*) into l_count from demo_users where user_name = p_username;
if l_count > 0 then
  -- First, we fetch the stored hashed password & expire date
  select password, expires_on into l_stored_password, l_expires_on
   from demo_users where user_name = p_username;

  -- Next, we check to see if the user's account is expired
  -- If it is, return FALSE
  if l_expires_on > sysdate or l_expires_on is null then

    -- If the account is not expired, we have to apply the custom hash
    -- function to the password
    l_password := custom_hash(p_username, p_password);

    -- Finally, we compare them to see if they are the same and return
    -- either TRUE or FALSE
    if l_password = l_stored_password then
      return true;
    else
      return false;
    end if;
  else
    return false;
  end if;
else
  -- The username provided is not in the DEMO_USERS table
  return false;
end if;
end;
/
/
CREATE UNIQUE INDEX  "SYS_C007686" ON  "COLLEGE" ("COLLEGEID") 
  ;CREATE UNIQUE INDEX  "SYS_C007687" ON  "COLLEGE" ("COLLEGENAME") 
  ;CREATE UNIQUE INDEX  "SYS_C007688" ON  "DEPARTMENT" ("DEPARTMENTID") 
  ;CREATE UNIQUE INDEX  "SYS_C007689" ON  "DEPARTMENT" ("DEPARTMENTNAME") 
  ;CREATE UNIQUE INDEX  "SYS_C007691" ON  "FIELDOFSTUDY" ("FIELDID") 
  ;CREATE UNIQUE INDEX  "SYS_C007692" ON  "FIELDOFSTUDY" ("FIELDNAME") 
  ;CREATE UNIQUE INDEX  "SYS_C007694" ON  "PROGRAMAWARD" ("AWARDID") 
  ;CREATE UNIQUE INDEX  "SYS_C007695" ON  "PROGRAMSTUDY" ("STUDYID") 
  ;CREATE UNIQUE INDEX  "SYS_C007697" ON  "ACADEMICYEAR" ("YEARID") 
  ;CREATE UNIQUE INDEX  "SYS_C007698" ON  "PROGRAMADMISSION" ("ADMISSIONID") 
  ;CREATE UNIQUE INDEX  "SYS_C007699" ON  "CURRICULUM" ("CURRICULUMID") 
  ;CREATE UNIQUE INDEX  "SYS_C007701" ON  "PROGRAMENTRY" ("ENTRYID") 
  ;CREATE UNIQUE INDEX  "SYS_C007703" ON  "STUDENT" ("STUDENTID") 
  ;
Rem No package found to generate DDL.
Rem No procedure found to generate DDL.
 CREATE SEQUENCE   "DEMO_USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ; CREATE SEQUENCE   "DEMO_PROD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ; CREATE SEQUENCE   "DEMO_ORD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 CACHE 20 NOORDER  NOCYCLE ; CREATE SEQUENCE   "DEMO_ORDER_ITEMS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ; CREATE SEQUENCE   "DEMO_CUST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
Rem No synonym found to generate DDL.
Rem No trigger found to generate DDL.
Rem No view found to generate DDL.
Rem No database link found to generate DDL.
Rem No type found to generate DDL.
Rem No materialized view found to generate DDL.